name: Build and Publish Plugin

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  prepare-release:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Extract current version
        id: version
        run: |
          CURRENT_VERSION=$(grep "version = " build.gradle.kts | cut -d'"' -f2)
          MAJOR=$(echo $CURRENT_VERSION | cut -d'.' -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d'.' -f2 | cut -d'-' -f1)
          NEW_MINOR=$((MINOR + 1))
          NEW_VERSION="$MAJOR.$NEW_MINOR-SNAPSHOT"
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create release branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout -b release/v${{ steps.version.outputs.current_version }}
          
          # Update versions
          sed -i "s/version = \"${{ steps.version.outputs.current_version }}\"/version = \"${{ steps.version.outputs.new_version }}\"/" build.gradle.kts
          sed -i "s/<version>${{ steps.version.outputs.current_version }}<\/version>/<version>${{ steps.version.outputs.new_version }}<\/version>/" src/main/resources/META-INF/plugin.xml
          
          git add build.gradle.kts src/main/resources/META-INF/plugin.xml
          git commit -m "Bump version to ${{ steps.version.outputs.new_version }}"
          git push origin release/v${{ steps.version.outputs.current_version }}

      - name: Create Release PR
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Release v${{ steps.version.outputs.current_version }}"
          body: "Release version ${{ steps.version.outputs.current_version }}"
          branch: "release/v${{ steps.version.outputs.current_version }}"
          base: main
          draft: false

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build and Publish
        run: |
          ./gradlew build -x test
          ./gradlew publishPlugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}

  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build
        run: ./gradlew build -x test 